//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseInfo
    {
        public int AutoId { get; set; }
        public int InfoId { get; set; }
        public string InfoName { get; set; }
        public string InfoDescription { get; set; }
        public string InfoContent { get; set; }
    }
}
