//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClerkGroup
    {
        public int AutoId { get; set; }
        public string GroupId { get; set; }
        public string GroupName { get; set; }
        public string GroupRemark { get; set; }
        public Nullable<bool> EnableCheckIn { get; set; }
        public Nullable<bool> EnableQuitDisher { get; set; }
        public Nullable<bool> EnableModifyNum { get; set; }
        public Nullable<bool> EnableModifyPrice { get; set; }
        public Nullable<bool> EnableDiscount { get; set; }
        public string DiscountId { get; set; }
        public Nullable<bool> EnableDiscountAll { get; set; }
        public Nullable<double> DiscountAllLimit { get; set; }
        public Nullable<bool> EnableDiscountMoney { get; set; }
        public Nullable<decimal> DiscountMoneyLimit { get; set; }
        public Nullable<bool> EnableArrear { get; set; }
        public Nullable<decimal> ArrearLimit { get; set; }
        public Nullable<bool> EnablePresent { get; set; }
        public Nullable<decimal> PresentLimit { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Updator { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Deletor { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    }
}
