//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClerkInfo
    {
        public int AutoId { get; set; }
        public string ClerkId { get; set; }
        public string ClerkName { get; set; }
        public string GroupId { get; set; }
        public string LoginName { get; set; }
        public string LoginPwd { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsEnable { get; set; }
        public string ClerkRemark { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Updator { get; set; }
        public Nullable<System.DateTime> UpdatorDate { get; set; }
        public string Deletor { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    }
}
