//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeskInfo
    {
        public int AutoId { get; set; }
        public string DeskId { get; set; }
        public string DeskName { get; set; }
        public string RoomId { get; set; }
        public string DeskRemark { get; set; }
        public bool Usable { get; set; }
        public Nullable<int> DinerNumber { get; set; }
        public string DinerCircumstance { get; set; }
        public Nullable<bool> IsRoom { get; set; }
        public string QRCode { get; set; }
        public Nullable<decimal> MinConsumption { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<int> UsedNum { get; set; }
        public string AreaID { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Updator { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Deletor { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    }
}
