//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuDetail
    {
        public int AutoId { get; set; }
        public string DisherId { get; set; }
        public string DisherCode { get; set; }
        public string DisherName { get; set; }
        public string DisherPicture { get; set; }
        public string DisherEnglishName { get; set; }
        public string DisherDescription { get; set; }
        public string DisherSubclassID1 { get; set; }
        public string DisherSubclassID2 { get; set; }
        public string DisherSize { get; set; }
        public Nullable<decimal> DisherPrice { get; set; }
        public Nullable<bool> DisherStatus { get; set; }
        public Nullable<decimal> DisherVipPrice { get; set; }
        public Nullable<decimal> DisherServicePrice { get; set; }
        public bool Usable { get; set; }
        public Nullable<double> DisherDiscount { get; set; }
        public string DepartmentId { get; set; }
        public Nullable<int> DisherPoint { get; set; }
        public Nullable<short> SourIndex { get; set; }
        public Nullable<short> SweetIndex { get; set; }
        public Nullable<short> SaltyIndex { get; set; }
        public Nullable<short> SpicyIndex { get; set; }
        public Nullable<short> Evaluate { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Updator { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public string Deletor { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<bool> CanSelect { get; set; }
    }
}
